AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

# All cops below exist to maximize compatibility with the Python client source code

Lint/UnreachableLoop:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - examples/chatbot_with_streaming.rb

Style/StringConcatenation:
  Exclude:
    - test/test_chat.rb
    - test/test_helper.rb
